// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: proto/osd.proto

package osd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	BucketId      string                 `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	VolumeId      string                 `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlockRequest) Reset() {
	*x = PutBlockRequest{}
	mi := &file_proto_osd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlockRequest) ProtoMessage() {}

func (x *PutBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlockRequest.ProtoReflect.Descriptor instead.
func (*PutBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_osd_proto_rawDescGZIP(), []int{0}
}

func (x *PutBlockRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PutBlockRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutBlockRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *PutBlockRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type PutBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlockResponse) Reset() {
	*x = PutBlockResponse{}
	mi := &file_proto_osd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlockResponse) ProtoMessage() {}

func (x *PutBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlockResponse.ProtoReflect.Descriptor instead.
func (*PutBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_osd_proto_rawDescGZIP(), []int{1}
}

func (x *PutBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	VolumeId      string                 `protobuf:"bytes,3,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_proto_osd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_osd_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlockRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetBlockRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GetBlockRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_proto_osd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_osd_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBlockResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_osd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_osd_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_osd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_osd_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_osd_proto protoreflect.FileDescriptor

const file_proto_osd_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/osd.proto\x12\x03osd\"s\n" +
	"\x0fPutBlockRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tbucket_id\x18\x03 \x01(\tR\bbucketId\x12\x1b\n" +
	"\tvolume_id\x18\x04 \x01(\tR\bvolumeId\"B\n" +
	"\x10PutBlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"_\n" +
	"\x0fGetBlockRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1b\n" +
	"\tvolume_id\x18\x03 \x01(\tR\bvolumeId\"V\n" +
	"\x10GetBlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xc0\x01\n" +
	"\n" +
	"OSDService\x127\n" +
	"\bPutBlock\x12\x14.osd.PutBlockRequest\x1a\x15.osd.PutBlockResponse\x127\n" +
	"\bGetBlock\x12\x14.osd.GetBlockRequest\x1a\x15.osd.GetBlockResponse\x12@\n" +
	"\vHealthCheck\x12\x17.osd.HealthCheckRequest\x1a\x18.osd.HealthCheckResponseB\x13Z\x11bharani/proto/osdb\x06proto3"

var (
	file_proto_osd_proto_rawDescOnce sync.Once
	file_proto_osd_proto_rawDescData []byte
)

func file_proto_osd_proto_rawDescGZIP() []byte {
	file_proto_osd_proto_rawDescOnce.Do(func() {
		file_proto_osd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_osd_proto_rawDesc), len(file_proto_osd_proto_rawDesc)))
	})
	return file_proto_osd_proto_rawDescData
}

var file_proto_osd_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_osd_proto_goTypes = []any{
	(*PutBlockRequest)(nil),     // 0: osd.PutBlockRequest
	(*PutBlockResponse)(nil),    // 1: osd.PutBlockResponse
	(*GetBlockRequest)(nil),     // 2: osd.GetBlockRequest
	(*GetBlockResponse)(nil),    // 3: osd.GetBlockResponse
	(*HealthCheckRequest)(nil),  // 4: osd.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 5: osd.HealthCheckResponse
}
var file_proto_osd_proto_depIdxs = []int32{
	0, // 0: osd.OSDService.PutBlock:input_type -> osd.PutBlockRequest
	2, // 1: osd.OSDService.GetBlock:input_type -> osd.GetBlockRequest
	4, // 2: osd.OSDService.HealthCheck:input_type -> osd.HealthCheckRequest
	1, // 3: osd.OSDService.PutBlock:output_type -> osd.PutBlockResponse
	3, // 4: osd.OSDService.GetBlock:output_type -> osd.GetBlockResponse
	5, // 5: osd.OSDService.HealthCheck:output_type -> osd.HealthCheckResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_osd_proto_init() }
func file_proto_osd_proto_init() {
	if File_proto_osd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_osd_proto_rawDesc), len(file_proto_osd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_osd_proto_goTypes,
		DependencyIndexes: file_proto_osd_proto_depIdxs,
		MessageInfos:      file_proto_osd_proto_msgTypes,
	}.Build()
	File_proto_osd_proto = out.File
	file_proto_osd_proto_goTypes = nil
	file_proto_osd_proto_depIdxs = nil
}
