// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.24.3
// source: proto/blockindex.proto

package blockindex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockIndexService_PutEntry_FullMethodName = "/blockindex.BlockIndexService/PutEntry"
	BlockIndexService_GetEntry_FullMethodName = "/blockindex.BlockIndexService/GetEntry"
	BlockIndexService_Exists_FullMethodName   = "/blockindex.BlockIndexService/Exists"
)

// BlockIndexServiceClient is the client API for BlockIndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlockIndex service for mapping block hashes to storage locations
type BlockIndexServiceClient interface {
	PutEntry(ctx context.Context, in *PutEntryRequest, opts ...grpc.CallOption) (*PutEntryResponse, error)
	GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error)
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
}

type blockIndexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockIndexServiceClient(cc grpc.ClientConnInterface) BlockIndexServiceClient {
	return &blockIndexServiceClient{cc}
}

func (c *blockIndexServiceClient) PutEntry(ctx context.Context, in *PutEntryRequest, opts ...grpc.CallOption) (*PutEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutEntryResponse)
	err := c.cc.Invoke(ctx, BlockIndexService_PutEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockIndexServiceClient) GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntryResponse)
	err := c.cc.Invoke(ctx, BlockIndexService_GetEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockIndexServiceClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, BlockIndexService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockIndexServiceServer is the server API for BlockIndexService service.
// All implementations should embed UnimplementedBlockIndexServiceServer
// for forward compatibility.
//
// BlockIndex service for mapping block hashes to storage locations
type BlockIndexServiceServer interface {
	PutEntry(context.Context, *PutEntryRequest) (*PutEntryResponse, error)
	GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error)
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
}

// UnimplementedBlockIndexServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockIndexServiceServer struct{}

func (UnimplementedBlockIndexServiceServer) PutEntry(context.Context, *PutEntryRequest) (*PutEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutEntry not implemented")
}
func (UnimplementedBlockIndexServiceServer) GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntry not implemented")
}
func (UnimplementedBlockIndexServiceServer) Exists(context.Context, *ExistsRequest) (*ExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedBlockIndexServiceServer) testEmbeddedByValue() {}

// UnsafeBlockIndexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockIndexServiceServer will
// result in compilation errors.
type UnsafeBlockIndexServiceServer interface {
	mustEmbedUnimplementedBlockIndexServiceServer()
}

func RegisterBlockIndexServiceServer(s grpc.ServiceRegistrar, srv BlockIndexServiceServer) {
	// If the following call panics, it indicates UnimplementedBlockIndexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockIndexService_ServiceDesc, srv)
}

func _BlockIndexService_PutEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockIndexServiceServer).PutEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockIndexService_PutEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockIndexServiceServer).PutEntry(ctx, req.(*PutEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockIndexService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockIndexServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockIndexService_GetEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockIndexServiceServer).GetEntry(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockIndexService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockIndexServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockIndexService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockIndexServiceServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockIndexService_ServiceDesc is the grpc.ServiceDesc for BlockIndexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockIndexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockindex.BlockIndexService",
	HandlerType: (*BlockIndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutEntry",
			Handler:    _BlockIndexService_PutEntry_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _BlockIndexService_GetEntry_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _BlockIndexService_Exists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blockindex.proto",
}
