// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: proto/blockindex.proto

package blockindex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutEntryRequest) Reset() {
	*x = PutEntryRequest{}
	mi := &file_proto_blockindex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEntryRequest) ProtoMessage() {}

func (x *PutEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockindex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEntryRequest.ProtoReflect.Descriptor instead.
func (*PutEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockindex_proto_rawDescGZIP(), []int{0}
}

func (x *PutEntryRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PutEntryRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *PutEntryRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *PutEntryRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type PutEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutEntryResponse) Reset() {
	*x = PutEntryResponse{}
	mi := &file_proto_blockindex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEntryResponse) ProtoMessage() {}

func (x *PutEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockindex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEntryResponse.ProtoReflect.Descriptor instead.
func (*PutEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockindex_proto_rawDescGZIP(), []int{1}
}

func (x *PutEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_proto_blockindex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockindex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockindex_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntryRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	BucketId      string                 `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	mi := &file_proto_blockindex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockindex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryResponse.ProtoReflect.Descriptor instead.
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockindex_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntryResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetEntryResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *GetEntryResponse) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *GetEntryResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *GetEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_proto_blockindex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockindex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockindex_proto_rawDescGZIP(), []int{4}
}

func (x *ExistsRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_proto_blockindex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockindex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockindex_proto_rawDescGZIP(), []int{5}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_proto_blockindex_proto protoreflect.FileDescriptor

const file_proto_blockindex_proto_rawDesc = "" +
	"\n" +
	"\x16proto/blockindex.proto\x12\n" +
	"blockindex\"w\n" +
	"\x0fPutEntryRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\x12\x1b\n" +
	"\tbucket_id\x18\x03 \x01(\tR\bbucketId\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"B\n" +
	"\x10PutEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\x0fGetEntryRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\x90\x01\n" +
	"\x10GetEntryResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\x12\x1b\n" +
	"\tbucket_id\x18\x03 \x01(\tR\bbucketId\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"#\n" +
	"\rExistsRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"(\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xe2\x01\n" +
	"\x11BlockIndexService\x12E\n" +
	"\bPutEntry\x12\x1b.blockindex.PutEntryRequest\x1a\x1c.blockindex.PutEntryResponse\x12E\n" +
	"\bGetEntry\x12\x1b.blockindex.GetEntryRequest\x1a\x1c.blockindex.GetEntryResponse\x12?\n" +
	"\x06Exists\x12\x19.blockindex.ExistsRequest\x1a\x1a.blockindex.ExistsResponseB\x1aZ\x18bharani/proto/blockindexb\x06proto3"

var (
	file_proto_blockindex_proto_rawDescOnce sync.Once
	file_proto_blockindex_proto_rawDescData []byte
)

func file_proto_blockindex_proto_rawDescGZIP() []byte {
	file_proto_blockindex_proto_rawDescOnce.Do(func() {
		file_proto_blockindex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blockindex_proto_rawDesc), len(file_proto_blockindex_proto_rawDesc)))
	})
	return file_proto_blockindex_proto_rawDescData
}

var file_proto_blockindex_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_blockindex_proto_goTypes = []any{
	(*PutEntryRequest)(nil),  // 0: blockindex.PutEntryRequest
	(*PutEntryResponse)(nil), // 1: blockindex.PutEntryResponse
	(*GetEntryRequest)(nil),  // 2: blockindex.GetEntryRequest
	(*GetEntryResponse)(nil), // 3: blockindex.GetEntryResponse
	(*ExistsRequest)(nil),    // 4: blockindex.ExistsRequest
	(*ExistsResponse)(nil),   // 5: blockindex.ExistsResponse
}
var file_proto_blockindex_proto_depIdxs = []int32{
	0, // 0: blockindex.BlockIndexService.PutEntry:input_type -> blockindex.PutEntryRequest
	2, // 1: blockindex.BlockIndexService.GetEntry:input_type -> blockindex.GetEntryRequest
	4, // 2: blockindex.BlockIndexService.Exists:input_type -> blockindex.ExistsRequest
	1, // 3: blockindex.BlockIndexService.PutEntry:output_type -> blockindex.PutEntryResponse
	3, // 4: blockindex.BlockIndexService.GetEntry:output_type -> blockindex.GetEntryResponse
	5, // 5: blockindex.BlockIndexService.Exists:output_type -> blockindex.ExistsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_blockindex_proto_init() }
func file_proto_blockindex_proto_init() {
	if File_proto_blockindex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blockindex_proto_rawDesc), len(file_proto_blockindex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_blockindex_proto_goTypes,
		DependencyIndexes: file_proto_blockindex_proto_depIdxs,
		MessageInfos:      file_proto_blockindex_proto_msgTypes,
	}.Build()
	File_proto_blockindex_proto = out.File
	file_proto_blockindex_proto_goTypes = nil
	file_proto_blockindex_proto_depIdxs = nil
}
