// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: proto/master.proto

package master

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterOSDRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OsdAddress     string                 `protobuf:"bytes,1,opt,name=osd_address,json=osdAddress,proto3" json:"osd_address,omitempty"`
	CellId         string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	AvailableSpace int64                  `protobuf:"varint,3,opt,name=available_space,json=availableSpace,proto3" json:"available_space,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterOSDRequest) Reset() {
	*x = RegisterOSDRequest{}
	mi := &file_proto_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOSDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOSDRequest) ProtoMessage() {}

func (x *RegisterOSDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOSDRequest.ProtoReflect.Descriptor instead.
func (*RegisterOSDRequest) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterOSDRequest) GetOsdAddress() string {
	if x != nil {
		return x.OsdAddress
	}
	return ""
}

func (x *RegisterOSDRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *RegisterOSDRequest) GetAvailableSpace() int64 {
	if x != nil {
		return x.AvailableSpace
	}
	return 0
}

type RegisterOSDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOSDResponse) Reset() {
	*x = RegisterOSDResponse{}
	mi := &file_proto_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOSDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOSDResponse) ProtoMessage() {}

func (x *RegisterOSDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOSDResponse.ProtoReflect.Descriptor instead.
func (*RegisterOSDResponse) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterOSDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterOSDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OsdAddress     string                 `protobuf:"bytes,1,opt,name=osd_address,json=osdAddress,proto3" json:"osd_address,omitempty"`
	Healthy        bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	AvailableSpace int64                  `protobuf:"varint,3,opt,name=available_space,json=availableSpace,proto3" json:"available_space,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetOsdAddress() string {
	if x != nil {
		return x.OsdAddress
	}
	return ""
}

func (x *HeartbeatRequest) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HeartbeatRequest) GetAvailableSpace() int64 {
	if x != nil {
		return x.AvailableSpace
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetOpenVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenVolumesRequest) Reset() {
	*x = GetOpenVolumesRequest{}
	mi := &file_proto_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenVolumesRequest) ProtoMessage() {}

func (x *GetOpenVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenVolumesRequest.ProtoReflect.Descriptor instead.
func (*GetOpenVolumesRequest) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{4}
}

func (x *GetOpenVolumesRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type GetOpenVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeIds     []string               `protobuf:"bytes,1,rep,name=volume_ids,json=volumeIds,proto3" json:"volume_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenVolumesResponse) Reset() {
	*x = GetOpenVolumesResponse{}
	mi := &file_proto_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenVolumesResponse) ProtoMessage() {}

func (x *GetOpenVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenVolumesResponse.ProtoReflect.Descriptor instead.
func (*GetOpenVolumesResponse) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{5}
}

func (x *GetOpenVolumesResponse) GetVolumeIds() []string {
	if x != nil {
		return x.VolumeIds
	}
	return nil
}

type CloseVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseVolumeRequest) Reset() {
	*x = CloseVolumeRequest{}
	mi := &file_proto_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseVolumeRequest) ProtoMessage() {}

func (x *CloseVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseVolumeRequest.ProtoReflect.Descriptor instead.
func (*CloseVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{6}
}

func (x *CloseVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type CloseVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseVolumeResponse) Reset() {
	*x = CloseVolumeResponse{}
	mi := &file_proto_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseVolumeResponse) ProtoMessage() {}

func (x *CloseVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseVolumeResponse.ProtoReflect.Descriptor instead.
func (*CloseVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{7}
}

func (x *CloseVolumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseVolumeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TriggerRepairRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FailedOsdAddress string                 `protobuf:"bytes,1,opt,name=failed_osd_address,json=failedOsdAddress,proto3" json:"failed_osd_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TriggerRepairRequest) Reset() {
	*x = TriggerRepairRequest{}
	mi := &file_proto_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRepairRequest) ProtoMessage() {}

func (x *TriggerRepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRepairRequest.ProtoReflect.Descriptor instead.
func (*TriggerRepairRequest) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{8}
}

func (x *TriggerRepairRequest) GetFailedOsdAddress() string {
	if x != nil {
		return x.FailedOsdAddress
	}
	return ""
}

type TriggerRepairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRepairResponse) Reset() {
	*x = TriggerRepairResponse{}
	mi := &file_proto_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRepairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRepairResponse) ProtoMessage() {}

func (x *TriggerRepairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRepairResponse.ProtoReflect.Descriptor instead.
func (*TriggerRepairResponse) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{9}
}

func (x *TriggerRepairResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerRepairResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_master_proto protoreflect.FileDescriptor

const file_proto_master_proto_rawDesc = "" +
	"\n" +
	"\x12proto/master.proto\x12\x06master\"w\n" +
	"\x12RegisterOSDRequest\x12\x1f\n" +
	"\vosd_address\x18\x01 \x01(\tR\n" +
	"osdAddress\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\x12'\n" +
	"\x0favailable_space\x18\x03 \x01(\x03R\x0eavailableSpace\"E\n" +
	"\x13RegisterOSDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"v\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vosd_address\x18\x01 \x01(\tR\n" +
	"osdAddress\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12'\n" +
	"\x0favailable_space\x18\x03 \x01(\x03R\x0eavailableSpace\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x15GetOpenVolumesRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\"7\n" +
	"\x16GetOpenVolumesResponse\x12\x1d\n" +
	"\n" +
	"volume_ids\x18\x01 \x03(\tR\tvolumeIds\"1\n" +
	"\x12CloseVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"E\n" +
	"\x13CloseVolumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"D\n" +
	"\x14TriggerRepairRequest\x12,\n" +
	"\x12failed_osd_address\x18\x01 \x01(\tR\x10failedOsdAddress\"G\n" +
	"\x15TriggerRepairResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x80\x03\n" +
	"\rMasterService\x12F\n" +
	"\vRegisterOSD\x12\x1a.master.RegisterOSDRequest\x1a\x1b.master.RegisterOSDResponse\x12@\n" +
	"\tHeartbeat\x12\x18.master.HeartbeatRequest\x1a\x19.master.HeartbeatResponse\x12O\n" +
	"\x0eGetOpenVolumes\x12\x1d.master.GetOpenVolumesRequest\x1a\x1e.master.GetOpenVolumesResponse\x12F\n" +
	"\vCloseVolume\x12\x1a.master.CloseVolumeRequest\x1a\x1b.master.CloseVolumeResponse\x12L\n" +
	"\rTriggerRepair\x12\x1c.master.TriggerRepairRequest\x1a\x1d.master.TriggerRepairResponseB\x16Z\x14bharani/proto/masterb\x06proto3"

var (
	file_proto_master_proto_rawDescOnce sync.Once
	file_proto_master_proto_rawDescData []byte
)

func file_proto_master_proto_rawDescGZIP() []byte {
	file_proto_master_proto_rawDescOnce.Do(func() {
		file_proto_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_master_proto_rawDesc), len(file_proto_master_proto_rawDesc)))
	})
	return file_proto_master_proto_rawDescData
}

var file_proto_master_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_master_proto_goTypes = []any{
	(*RegisterOSDRequest)(nil),     // 0: master.RegisterOSDRequest
	(*RegisterOSDResponse)(nil),    // 1: master.RegisterOSDResponse
	(*HeartbeatRequest)(nil),       // 2: master.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 3: master.HeartbeatResponse
	(*GetOpenVolumesRequest)(nil),  // 4: master.GetOpenVolumesRequest
	(*GetOpenVolumesResponse)(nil), // 5: master.GetOpenVolumesResponse
	(*CloseVolumeRequest)(nil),     // 6: master.CloseVolumeRequest
	(*CloseVolumeResponse)(nil),    // 7: master.CloseVolumeResponse
	(*TriggerRepairRequest)(nil),   // 8: master.TriggerRepairRequest
	(*TriggerRepairResponse)(nil),  // 9: master.TriggerRepairResponse
}
var file_proto_master_proto_depIdxs = []int32{
	0, // 0: master.MasterService.RegisterOSD:input_type -> master.RegisterOSDRequest
	2, // 1: master.MasterService.Heartbeat:input_type -> master.HeartbeatRequest
	4, // 2: master.MasterService.GetOpenVolumes:input_type -> master.GetOpenVolumesRequest
	6, // 3: master.MasterService.CloseVolume:input_type -> master.CloseVolumeRequest
	8, // 4: master.MasterService.TriggerRepair:input_type -> master.TriggerRepairRequest
	1, // 5: master.MasterService.RegisterOSD:output_type -> master.RegisterOSDResponse
	3, // 6: master.MasterService.Heartbeat:output_type -> master.HeartbeatResponse
	5, // 7: master.MasterService.GetOpenVolumes:output_type -> master.GetOpenVolumesResponse
	7, // 8: master.MasterService.CloseVolume:output_type -> master.CloseVolumeResponse
	9, // 9: master.MasterService.TriggerRepair:output_type -> master.TriggerRepairResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_master_proto_init() }
func file_proto_master_proto_init() {
	if File_proto_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_master_proto_rawDesc), len(file_proto_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_master_proto_goTypes,
		DependencyIndexes: file_proto_master_proto_depIdxs,
		MessageInfos:      file_proto_master_proto_msgTypes,
	}.Build()
	File_proto_master_proto = out.File
	file_proto_master_proto_goTypes = nil
	file_proto_master_proto_depIdxs = nil
}
