// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.24.3
// source: proto/master.proto

package master

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterService_RegisterOSD_FullMethodName    = "/master.MasterService/RegisterOSD"
	MasterService_Heartbeat_FullMethodName      = "/master.MasterService/Heartbeat"
	MasterService_GetOpenVolumes_FullMethodName = "/master.MasterService/GetOpenVolumes"
	MasterService_CloseVolume_FullMethodName    = "/master.MasterService/CloseVolume"
	MasterService_TriggerRepair_FullMethodName  = "/master.MasterService/TriggerRepair"
)

// MasterServiceClient is the client API for MasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Master service for coordinating repairs and volume management
type MasterServiceClient interface {
	RegisterOSD(ctx context.Context, in *RegisterOSDRequest, opts ...grpc.CallOption) (*RegisterOSDResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetOpenVolumes(ctx context.Context, in *GetOpenVolumesRequest, opts ...grpc.CallOption) (*GetOpenVolumesResponse, error)
	CloseVolume(ctx context.Context, in *CloseVolumeRequest, opts ...grpc.CallOption) (*CloseVolumeResponse, error)
	TriggerRepair(ctx context.Context, in *TriggerRepairRequest, opts ...grpc.CallOption) (*TriggerRepairResponse, error)
}

type masterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterServiceClient(cc grpc.ClientConnInterface) MasterServiceClient {
	return &masterServiceClient{cc}
}

func (c *masterServiceClient) RegisterOSD(ctx context.Context, in *RegisterOSDRequest, opts ...grpc.CallOption) (*RegisterOSDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterOSDResponse)
	err := c.cc.Invoke(ctx, MasterService_RegisterOSD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MasterService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) GetOpenVolumes(ctx context.Context, in *GetOpenVolumesRequest, opts ...grpc.CallOption) (*GetOpenVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOpenVolumesResponse)
	err := c.cc.Invoke(ctx, MasterService_GetOpenVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) CloseVolume(ctx context.Context, in *CloseVolumeRequest, opts ...grpc.CallOption) (*CloseVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseVolumeResponse)
	err := c.cc.Invoke(ctx, MasterService_CloseVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) TriggerRepair(ctx context.Context, in *TriggerRepairRequest, opts ...grpc.CallOption) (*TriggerRepairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerRepairResponse)
	err := c.cc.Invoke(ctx, MasterService_TriggerRepair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServiceServer is the server API for MasterService service.
// All implementations should embed UnimplementedMasterServiceServer
// for forward compatibility.
//
// Master service for coordinating repairs and volume management
type MasterServiceServer interface {
	RegisterOSD(context.Context, *RegisterOSDRequest) (*RegisterOSDResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetOpenVolumes(context.Context, *GetOpenVolumesRequest) (*GetOpenVolumesResponse, error)
	CloseVolume(context.Context, *CloseVolumeRequest) (*CloseVolumeResponse, error)
	TriggerRepair(context.Context, *TriggerRepairRequest) (*TriggerRepairResponse, error)
}

// UnimplementedMasterServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterServiceServer struct{}

func (UnimplementedMasterServiceServer) RegisterOSD(context.Context, *RegisterOSDRequest) (*RegisterOSDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterOSD not implemented")
}
func (UnimplementedMasterServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMasterServiceServer) GetOpenVolumes(context.Context, *GetOpenVolumesRequest) (*GetOpenVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenVolumes not implemented")
}
func (UnimplementedMasterServiceServer) CloseVolume(context.Context, *CloseVolumeRequest) (*CloseVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseVolume not implemented")
}
func (UnimplementedMasterServiceServer) TriggerRepair(context.Context, *TriggerRepairRequest) (*TriggerRepairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerRepair not implemented")
}
func (UnimplementedMasterServiceServer) testEmbeddedByValue() {}

// UnsafeMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServiceServer will
// result in compilation errors.
type UnsafeMasterServiceServer interface {
	mustEmbedUnimplementedMasterServiceServer()
}

func RegisterMasterServiceServer(s grpc.ServiceRegistrar, srv MasterServiceServer) {
	// If the following call panics, it indicates UnimplementedMasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterService_ServiceDesc, srv)
}

func _MasterService_RegisterOSD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterOSDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).RegisterOSD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_RegisterOSD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).RegisterOSD(ctx, req.(*RegisterOSDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_GetOpenVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).GetOpenVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_GetOpenVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).GetOpenVolumes(ctx, req.(*GetOpenVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_CloseVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).CloseVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_CloseVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).CloseVolume(ctx, req.(*CloseVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_TriggerRepair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRepairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).TriggerRepair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_TriggerRepair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).TriggerRepair(ctx, req.(*TriggerRepairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterService_ServiceDesc is the grpc.ServiceDesc for MasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "master.MasterService",
	HandlerType: (*MasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterOSD",
			Handler:    _MasterService_RegisterOSD_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MasterService_Heartbeat_Handler,
		},
		{
			MethodName: "GetOpenVolumes",
			Handler:    _MasterService_GetOpenVolumes_Handler,
		},
		{
			MethodName: "CloseVolume",
			Handler:    _MasterService_CloseVolume_Handler,
		},
		{
			MethodName: "TriggerRepair",
			Handler:    _MasterService_TriggerRepair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/master.proto",
}
